### ISSUE TITLE
rclone 挂载出错

### ISSUE THREAD

**Issue by qi-mooo** [ShiroNeri4u/Neribox#3]
他为什么要在根目录上创建

mkdir: '/Cloud': Read-only file system
touch: '/Cloud/.nomedia': No such file or directory
chown: /Cloud/.nomedia: No such file or directory
chmod: /Cloud/.nomedia: No such file or directory
mount: '/Cloud/.AList'->'/mnt/androidwritable/0/emulated/0/AList': No such file or directory
mount: '/Cloud/.AList'->'/mnt/installer/0/emulated/0/AList': No such file or directory
mount: '/Cloud/.AList'->'/mnt/user/0/emulated/0/AList': No such file or directory
2024/02/08 08:04:03 mount helper error: fusermount3: bad mount point /Cloud/.AList: No such file or directory
2024/02/08 08:04:03 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
mkdir: '/Cloud': Read-only file system
touch: '/Cloud/.nomedia': No such file or directory
chown: /Cloud/.nomedia: No such file or directory
chmod: /Cloud/.nomedia: No such file or directory
mount: '/Cloud/.AList'->'/mnt/androidwritable/0/emulated/0/AList': No such file or directory
mount: '/Cloud/.AList'->'/mnt/installer/0/emulated/0/AList': No such file or directory
mount: '/Cloud/.AList'->'/mnt/user/0/emulated/0/AList': No such file or directory
2024/02/08 08:04:07 mount helper error: fusermount3: bad mount point /Cloud/.AList: No such file or directory
2024/02/08 08:04:07 Fatal error: failed to mount FUSE fs: fusermount: exit status 1

**Comment by KazamataNeriQwQ** [comment]
检查配置文件中
MOUNTPATH=/data/adb/Neribox
选项是否为空

**Comment by qi-mooo** [comment]
> 检查配置文件中 MOUNTPATH=/data/adb/Neribox 选项是否为空

确实是空的，已经解决
